GIT_COPTS = [
    "-g",
    "-O2",
    "-Wall",
    "-I.",
    "-DHAVE_ALLOCA_H",
    "-DUSE_CURL_FOR_IMAP_SEND",
    "-DSUPPORTS_SIMPLE_IPC",
    "-DSHA1_DC",
    "-DSHA1DC_NO_STANDARD_INCLUDES",
    "-DSHA1DC_INIT_SAFE_HASH_DEFAULT=0",
    '-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\\"git-compat-util.h\\"',
    '-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\\"git-compat-util.h\\"',
    "-DSHA256_BLK",
    "-DHAVE_PATHS_H",
    "-DHAVE_DEV_TTY",
    "-DHAVE_CLOCK_GETTIME",
    "-DHAVE_CLOCK_MONOTONIC",
    "-DHAVE_SYNC_FILE_RANGE",
    "-DHAVE_SYSINFO",
    "-DHAVE_GETDELIM",
    "-DHAVE_GETRANDOM",
    "-DFREAD_READS_DIRECTORIES",
    "-DNO_STRLCPY",
    '-DSHELL_PATH=\\"/bin/sh\\"',
    '-DGIT_HTML_PATH=\\"share/doc/git-doc\\"',
    '-DGIT_MAN_PATH=\\"share/man\\"',
    '-DGIT_INFO_PATH=\\"share/info\\"',
    '-DGIT_EXEC_PATH=\\"libexec/git-core\\"',
    '-DGIT_LOCALE_PATH=\\"share/locale\\"',
    '-DBINDIR=\\"bin\\"',
    '-DFALLBACK_RUNTIME_PREFIX=\\"\\"',
    '-DDEFAULT_GIT_TEMPLATE_DIR=\\"share/git-core/templates\\"',
    '-DETC_GITCONFIG=\\"etc/gitconfig\\"',
    '-DETC_GITATTRIBUTES=\\"etc/gitattributes\\"',
    '-DPAGER_ENV=\\"LESS=FRX\\040LV=-c\\"',
] + select({
    "@platforms//cpu:aarch64": ['-DGIT_HOST_CPU=\\"aarch64\\"'],
    "@platforms//cpu:x86_64": ['-DGIT_HOST_CPU=\\"x86_64\\"'],
    "//conditions:default": ['-DGIT_HOST_CPU=\\"unknown\\"'],
})

GIT_LINKOPTS = ["-lpthread"]
